### ISSUE TITLE
log4rs_gelf returns always SetLoggerError

### ISSUE THREAD

**Issue by lukaszaoralek** [ovh/rust-log4rs-gelf#1]
I've got SetLoggerError(()) when I call log4rs_gelf::init_file("/tmp/log4rs.yml", None);

The problem is the method init_file call set_logger_inner twice. The first call occurs when the BufferAppender is build and second one when the method init_config is called.

The same problem occurs when I follow the example with programmatically constructing the config.

**Comment by zenria** [comment]
Any plan to fix this @cdumay ?

**Comment by cdumay** [comment]
released log4rs-gelf 0.1.2 and gelf_logger 0.1.3

**Comment by cdumay** [comment]
Make sure to update dependencies.
